price_skumria = float(input())
price_caca = float(input())
kilos_palamud = float(input())
kilos_safrid = float(input())
kilos_midi = int(input())
price_palamud = float(price_skumria + price_skumria * 0.6)
price_safrid = float(price_caca + price_caca * 0.8)
price_midi = float(7.5)
total_palamud = float(kilos_palamud * price_palamud)
total_safrid  = float(kilos_safrid * price_safrid)
total_midi = float(kilos_midi * price_midi)
total = float(total_midi + total_safrid + total_palamud)

print("%.2f" % total)
